- SkinName: "Gosha_Lea"
  Player_List: true
  Character_ID: "Gosha_Lea"
  OtherSprite_Path: "Gosha/Lea"

- SkinName: "Gosha_Lea2"
  Player_List: true
  Character_ID: "Gosha_Lea2"
  OtherSprite_Path: "Gosha/Lea"