- SkinName: "Gosha_Lea"
  Player_List: true
  Character_ID: "Gosha_Lea"
  OtherSprite_Path: "Gosha/Lea"

- SkinName: "Gosha_Shizuka"
  Player_List: true
  Character_ID: "Gosha_Shizuka"
  OtherSprite_Path: "Gosha/Shizuka"